name: flutter_easy_start_project
description: "flutter_easy_start_project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.2
  flex_color_scheme: ^7.3.1
  provider: ^6.1.2
  json_annotation: ^4.8.1
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  fl_chart: ^0.64.0
  copy_with_extension_gen: ^5.0.4

  cupertino_icons: ^1.0.6

  flutter_easy_start_project_generator:
    path: ./gen

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  test: ^1.24.3
  
flutter:
  uses-material-design: true
