name: flutter_easy_start_project
description: "flutter_easy_start_project"
repository: https://github.com/Vantus555/flutter_easy_start_project
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.0
  flex_color_scheme: ^7.3.1
  provider: ^6.1.2
  json_annotation: ^4.9.0
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  copy_with_extension_gen: ^5.0.4

  cupertino_icons: ^1.0.6

  flutter_easy_start_project_generator:
    path: ./gen

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  test: ^1.24.9
  
flutter:
  uses-material-design: true
