builders:
  FespNodeBuilders:
    import: 'package:fesp_node_builders/fesp_node_builders.dart'
    builder_factories: ['FespNodeBuilders']
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]