builders:
  FespNodeBuilders:
    import: 'package:flutter_easy_start_project_generator/fesp_node_builders.dart'
    builder_factories: ['FespNodeBuilders']
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  FespReflectorBuilder:
    import: 'package:flutter_easy_start_project_generator/fesp_reflector_builder.dart'
    builder_factories: ['FespReflectorBuilder']
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]