name: flutter_easy_start_project_generator
description: "flutter_easy_start_project_generator"
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  source_gen:

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
