name: flutter_easy_start_project_generator
description: "flutter_easy_start_project_generator"
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  source_gen:
  json_annotation: ^4.8.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
